#!/bin/bash

set -e
set -u
set -o pipefail

DIST=${1:?Specify the distrubution name}
PLATFORM=${2:-amd64}

BASENAME=bitmoa/minideb
DOCKER_REGISTRY=${DOCKER_REGISTRY:-"ghcr.io"}

if [ -n "${DOCKER_PASSWORD:-}" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "${DOCKER_REGISTRY}"
fi

ENABLE_COSIGN=${ENABLE_COSIGN:-0}

push() {
    local dist="$1"
    docker tag "${BASENAME}:${dist}" "${DOCKER_REGISTRY}/${BASENAME}:${dist}"
    docker push "${DOCKER_REGISTRY}/${BASENAME}:${dist}"
    if [ "${ENABLE_COSIGN}" == "1" ]; then
        IMAGE_DIGEST="$(docker inspect --format='{{index .RepoDigests 0}}' "${DOCKER_REGISTRY}/${BASENAME}:${dist}" | cut -d'@' -f2)"
        cosign sign --yes "${DOCKER_REGISTRY}/${BASENAME}:${dist}@${IMAGE_DIGEST}"
        cosign verify "${DOCKER_REGISTRY}/${BASENAME}:${dist}" ${COSIGN_VERIFY_ARGS}
    fi
}

push "$DIST-${PLATFORM}"
